<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('personnel_certifications', function (Blueprint $table) {
            $table->id();
            $table->text('name_address')->nullable();
            $table->text('postcode')->nullable();
            $table->text('tel')->nullable();
            $table->text('fax')->nullable();
            $table->text('email')->nullable();
            $table->text('website')->nullable();
            $table->text('contact_name')->nullable();
            $table->text('designation')->nullable();
            $table->text('person_address')->nullable();
            $table->text('person_postcode')->nullable();
            $table->text('person_tel')->nullable();
            $table->text('person_cal_no')->nullable();
            $table->text('person_fax')->nullable();
            $table->text('person_email')->nullable();
            $table->text('person_detail')->nullable();
            $table->text('chack_accreditation')->nullable();
            $table->text('chack_extension')->nullable();
            $table->text('chack_manual')->nullable();
            $table->text('chack_procedures')->nullable();
            $table->text('chack_applicant')->nullable();
            $table->text('chack_agreement')->nullable();
            $table->text('chack_certified')->nullable();
            $table->text('selves_title')->nullable();
            $table->text('selves_name')->nullable();
            $table->text('selves_position')->nullable();
            $table->text('selves_parent_organization')->nullable();
            $table->text('selves_parent_address')->nullable();
            $table->text('selves_postcode')->nullable();
            $table->text('selves_tel')->nullable();
            $table->text('selves_fax')->nullable();
            $table->text('selves_individual')->nullable();
            $table->text('selves_public')->nullable();
            $table->text('selves_private')->nullable();
            $table->text('selves_learned')->nullable();
            $table->text('selves_industry')->nullable();
            $table->text('selves_academic')->nullable();
            $table->text('selves_govt')->nullable();
            $table->text('selves_part_academic')->nullable();
            $table->text('selves_other_describe')->nullable();
            $table->text('selves_activity')->nullable();
            $table->text('selves_describe_activity')->nullable();
            $table->text('staff_chief_name')->nullable();
            $table->text('staff_chief_qualifications')->nullable();
            $table->text('staff_chief_relevant')->nullable();
            $table->text('staff_chief_exp')->nullable();
            $table->text('staff_quality_name')->nullable();
            $table->text('staff_quality_qualifications')->nullable();
            $table->text('staff_quality_relevant')->nullable();
            $table->text('staff_quality_exp')->nullable();
            $table->text('staff_manage_name')->nullable();
            $table->text('staff_manage_qualifications')->nullable();
            $table->text('staff_manage_relevant')->nullable();
            $table->text('staff_manage_exp')->nullable();
            $table->text('staff_expert_name')->nullable();
            $table->text('staff_expert_qualifications')->nullable();
            $table->text('staff_expert_field')->nullable();
            $table->text('staff_expert_exp')->nullable();
            $table->text('staff_sub_name')->nullable();
            $table->text('staff_sub_qualifications')->nullable();
            $table->text('staff_sub_field')->nullable();
            $table->text('staff_sub_exp')->nullable();
            $table->text('scop_check_person')->nullable();
            $table->text('scop_check_driving')->nullable();
            $table->text('scop_check_joining')->nullable();
            $table->text('scop_check_expert')->nullable();
            $table->text('scop_check_real')->nullable();
            $table->text('scop_check_corrosion')->nullable();
            $table->text('scop_check_sensoric')->nullable();
            $table->text('scop_check_it')->nullable();
            $table->text('scop_check_quality')->nullable();
            $table->text('scop_check_env')->nullable();
            $table->text('scop_check_traffic')->nullable();
            $table->text('scop_check_trainer')->nullable();
            $table->text('scop_check_wound')->nullable();
            $table->text('scop_check_other')->nullable();
            $table->text('scop_by_hwom')->nullable();
            $table->text('scop_maintained')->nullable();
            $table->text('quality_org_manual')->nullable();
            $table->text('quality_org_manual_comment')->nullable();
            $table->text('quality_org_policy')->nullable();
            $table->text('quality_org_policy_comment')->nullable();
            $table->text('quality_org_doc')->nullable();
            $table->text('quality_org_doc_comment')->nullable();
            $table->text('quality_org_contain')->nullable();
            $table->text('quality_org_contain_comment')->nullable();
            $table->text('quality_org_cbp')->nullable();
            $table->text('quality_org_cbp_comment')->nullable();
            $table->text('quality_org_cb')->nullable();
            $table->text('quality_org_cb_comment')->nullable();
            $table->text('quality_org_impartiality')->nullable();
            $table->text('quality_org_impartiality_comment')->nullable();
            $table->text('quality_org_necessary')->nullable();
            $table->text('quality_org_necessary_comment')->nullable();
            $table->text('quality_res_cbp')->nullable();
            $table->text('quality_res_cbp_comment')->nullable();
            $table->text('quality_res_defined')->nullable();
            $table->text('quality_res_defined_comment')->nullable();
            $table->text('quality_res_declared')->nullable();
            $table->text('quality_res_declared_comment')->nullable();
            $table->text('quality_res_out')->nullable();
            $table->text('quality_res_out_comment')->nullable();
            $table->text('quality_record_cbp')->nullable();
            $table->text('quality_record_cbp_comment')->nullable();
            $table->text('quality_record_maintain')->nullable();
            $table->text('quality_record_maintain_comment')->nullable();
            $table->text('quality_certified_cbp')->nullable();
            $table->text('quality_certified_cbp_comment')->nullable();
            $table->text('quality_certified_process')->nullable();
            $table->text('quality_certified_process_comment')->nullable();
            $table->text('quality_req_cbp')->nullable();
            $table->text('quality_req_cbp_comment')->nullable();
            $table->text('quality_req_complete')->nullable();
            $table->text('quality_req_complete_comment')->nullable();
            $table->text('quality_req_examinat')->nullable();
            $table->text('quality_req_examinat_comment')->nullable();
            $table->text('quality_req_decision')->nullable();
            $table->text('quality_req_decision_comment')->nullable();
            $table->text('quality_req_suspend')->nullable();
            $table->text('quality_req_suspend_comment')->nullable();
            $table->text('quality_req_policy')->nullable();
            $table->text('quality_req_policy_comment')->nullable();
            $table->text('quality_req_appeals')->nullable();
            $table->text('quality_req_appeals_comment')->nullable();
            $table->text('quality_manage_cbp')->nullable();
            $table->text('quality_manage_cbp_comment')->nullable();
            $table->text('quality_manage_fully')->nullable();
            $table->text('quality_manage_fully_comment')->nullable();
            $table->text('quality_manage_record')->nullable();
            $table->text('quality_manage_record_comment')->nullable();
            $table->text('quality_manage_pcb')->nullable();
            $table->text('quality_manage_pcb_comment')->nullable();
            $table->text('quality_manage_proced')->nullable();
            $table->text('quality_manage_proced_comment')->nullable();
            $table->text('quality_manage_correct')->nullable();
            $table->text('quality_manage_correct_comment')->nullable();
            $table->text('quality_complies_check')->nullable();
            $table->text('quality_non_compliance')->nullable();
            $table->text('quality_rectified_date')->nullable();
            $table->text('approvals_name')->nullable();
            $table->text('approvals_scope')->nullable();
            $table->text('approvals_start_date')->nullable();
            $table->text('approvals_end_date')->nullable();
            $table->text('declaration_new_applicant')->nullable();
            $table->text('declaration_extension')->nullable();
            $table->text('declaration_signed')->nullable();
            $table->text('category')->nullable();

            $table->unsignedBigInteger('user_id')->nullable();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('personnel_certifications');
    }
};
