<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('product_certifications', function (Blueprint $table) {
            $table->id();
            $table->text('product')->nullable();
            $table->text('certification_body')->nullable();
            $table->text('name_address')->nullable();
            $table->text('postcode')->nullable();
            $table->text('tel')->nullable();
            $table->text('fax')->nullable();
            $table->text('email')->nullable();
            $table->text('website')->nullable();
            $table->text('contact_name')->nullable();
            $table->text('designation')->nullable();
            $table->text('person_address')->nullable();
            $table->text('person_postcode')->nullable();
            $table->text('person_tel')->nullable();
            $table->text('person_fax')->nullable();
            $table->text('person_email')->nullable();
            $table->text('person_detail')->nullable();
            $table->text('chack_accreditation')->nullable();
            $table->text('chack_product')->nullable();
            $table->text('chack_extension')->nullable();
            $table->text('chack_manual')->nullable();
            $table->text('chack_procedures')->nullable();
            $table->text('chack_certified')->nullable();
            $table->text('chack_scheme')->nullable();
            $table->text('chack_applicant')->nullable();
            $table->text('selves_title')->nullable();
            $table->text('selves_name')->nullable();
            $table->text('selves_position')->nullable();
            $table->text('selves_parent_organization')->nullable();
            $table->text('selves_parent_relationship')->nullable();
            $table->text('selves_parent_address')->nullable();
            $table->text('selves_postcode')->nullable();
            $table->text('selves_tel')->nullable();
            $table->text('selves_fax')->nullable();
            $table->text('selves_invoicing_organization')->nullable();
            $table->text('selves_invoicing_address')->nullable();
            $table->text('selves_invoicing_postcode')->nullable();
            $table->text('selves_invoicing_tel')->nullable();
            $table->text('selves_invoicing_fax')->nullable();
            $table->text('selves_invoicing_email')->nullable();
            $table->text('selves_individual')->nullable();
            $table->text('selves_public')->nullable();
            $table->text('selves_private')->nullable();
            $table->text('selves_learned')->nullable();
            $table->text('selves_industry')->nullable();
            $table->text('selves_academic')->nullable();
            $table->text('selves_other_describe')->nullable();
            $table->text('selves_activity')->nullable();
            $table->text('selves_cab_activity')->nullable();
            $table->text('selves_consult_name')->nullable();
            $table->text('selves_consult_organization')->nullable();
            $table->text('selves_consult_address')->nullable();
            $table->text('selves_consult_postcode')->nullable();
            $table->text('selves_consult_tel')->nullable();
            $table->text('selves_consult_fax')->nullable();
            $table->text('selves_consult_email')->nullable();
            $table->text('staff_chief_name')->nullable();
            $table->text('staff_chief_qualifications')->nullable();
            $table->text('staff_chief_relevant')->nullable();
            $table->text('staff_chief_exp')->nullable();
            $table->text('staff_quality_name')->nullable();
            $table->text('staff_quality_qualifications')->nullable();
            $table->text('staff_quality_relevant')->nullable();
            $table->text('staff_quality_exp')->nullable();
            $table->text('staff_manage_name')->nullable();
            $table->text('staff_manage_qualifications')->nullable();
            $table->text('staff_manage_relevant')->nullable();
            $table->text('staff_manage_exp')->nullable();
            $table->text('staff_auditor_name')->nullable();
            $table->text('staff_auditor_qualifications')->nullable();
            $table->text('staff_auditor_field')->nullable();
            $table->text('staff_auditor_exp')->nullable();
            $table->text('staff_list_name')->nullable();
            $table->text('staff_list_qualifications')->nullable();
            $table->text('staff_list_field')->nullable();
            $table->text('staff_list_exp')->nullable();
            $table->text('scop_product')->nullable();
            $table->text('scop_according')->nullable();
            $table->text('scop_standard')->nullable();
            $table->text('scop_countries')->nullable();
            $table->text('scop_equipment')->nullable();
            $table->text('scop_last_date')->nullable();
            $table->text('scop_next_date')->nullable();
            $table->text('scop_calibration')->nullable();
            $table->text('scop_details')->nullable();
            $table->text('scop_comments')->nullable();
            $table->text('approvals_name')->nullable();
            $table->text('approvals_scope')->nullable();
            $table->text('approvals_start_date')->nullable();
            $table->text('approvals_end_date')->nullable();
            $table->text('declaration_new_applicant')->nullable();
            $table->text('declaration_product')->nullable();
            $table->text('declaration_extension')->nullable();
            $table->text('declaration_signed')->nullable();
            $table->text('declaration_date')->nullable();
            $table->text('org_quality')->nullable();
            $table->text('org_quality_comment')->nullable();
            $table->text('org_policy')->nullable();
            $table->text('org_policy_comment')->nullable();
            $table->text('org_doc')->nullable();
            $table->text('org_doc_comment')->nullable();
            $table->text('org_contain')->nullable();
            $table->text('org_contain_comment')->nullable();
            $table->text('org_qmr')->nullable();
            $table->text('org_qmr_comment')->nullable();
            $table->text('org_pcb')->nullable();
            $table->text('org_pcb_comment')->nullable();
            $table->text('org_sufficient')->nullable();
            $table->text('org_sufficient_comment')->nullable();
            $table->text('quality_doc')->nullable();
            $table->text('quality_doc_comment')->nullable();
            $table->text('quality_frequency')->nullable();
            $table->text('quality_frequency_comment')->nullable();
            $table->text('quality_record')->nullable();
            $table->text('quality_record_comment')->nullable();
            $table->text('quality_pcb')->nullable();
            $table->text('quality_pcb_comment')->nullable();
            $table->text('quality_reviews')->nullable();
            $table->text('quality_reviews_comment')->nullable();
            $table->text('certification_quality')->nullable();
            $table->text('certification_quality_comment')->nullable();
            $table->text('certification_appropriate')->nullable();
            $table->text('certification_appropriate_comment')->nullable();
            $table->text('certification_doc')->nullable();
            $table->text('certification_doc_comment')->nullable();
            $table->text('procedures_fully')->nullable();
            $table->text('procedures_fully_comment')->nullable();
            $table->text('procedures_doc')->nullable();
            $table->text('procedures_doc_comment')->nullable();
            $table->text('record_system')->nullable();
            $table->text('record_system_comment')->nullable();
            $table->text('record_arrange')->nullable();
            $table->text('record_arrange_comment')->nullable();
            $table->text('record_period')->nullable();
            $table->text('record_period_comment')->nullable();
            $table->text('complaint_pcb')->nullable();
            $table->text('complaint_pcb_comment')->nullable();
            $table->text('complaint_record')->nullable();
            $table->text('complaint_record_comment')->nullable();
            $table->text('sub_pcb')->nullable();
            $table->text('sub_pcb_comment')->nullable();
            $table->text('outside_pcb')->nullable();
            $table->text('outside_pcb_comment')->nullable();
            $table->text('outside_record')->nullable();
            $table->text('outside_record_comment')->nullable();
            $table->text('complies_check')->nullable();
            $table->text('globalgap_check')->nullable();
            $table->text('compliance_check')->nullable();
            $table->text('rectified_date')->nullable();

            $table->text('category')->nullable();

            $table->unsignedBigInteger('user_id')->nullable();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('product_certifications');
    }
};
