<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('halal_certification_bodies', function (Blueprint $table) {
            $table->id();
            $table->text('hala_body')->nullable();
            $table->text('address')->nullable();
            $table->text('postcode')->nullable();
            $table->text('tel')->nullable();
            $table->text('fax')->nullable();
            $table->text('contact_name')->nullable();
            $table->text('designation')->nullable();
            $table->text('person_address')->nullable();
            $table->text('person_postcode')->nullable();
            $table->text('person_tel')->nullable();
            $table->text('person_fax')->nullable();
            $table->text('person_email')->nullable();
            $table->text('person_detail')->nullable();
            $table->text('chack_accreditation')->nullable();
            $table->text('chack_laboratory')->nullable();
            $table->text('chack_extension')->nullable();
            $table->text('chack_hcb')->nullable();
            $table->text('chack_Applicant')->nullable();
            $table->text('selves_title')->nullable();
            $table->text('selves_name')->nullable();
            $table->text('selves_position')->nullable();
            $table->text('selves_parent_organization')->nullable();
            $table->text('selves_address')->nullable();
            $table->text('selves_postcode')->nullable();
            $table->text('selves_tel')->nullable();
            $table->text('selves_fax')->nullable();
            $table->text('selves_invoicing_organization')->nullable();
            $table->text('selves_invoicing_address')->nullable();
            $table->text('selves_invoicing_postcode')->nullable();
            $table->text('selves_invoicing_tel')->nullable();
            $table->text('selves_invoicing_fax')->nullable();
            $table->text('selves_individual')->nullable();
            $table->text('selves_public')->nullable();
            $table->text('selves_private')->nullable();
            $table->text('selves_learned')->nullable();
            $table->text('selves_industry')->nullable();
            $table->text('selves_academic')->nullable();
            $table->text('selves_other_describe')->nullable();
            $table->text('selves_activities')->nullable();
            $table->text('selves_cab_activities')->nullable();
            $table->text('staff_chief_name')->nullable();
            $table->text('staff_chief_religion')->nullable();
            $table->text('staff_chief_qualifications')->nullable();
            $table->text('staff_chief_relevant')->nullable();
            $table->text('staff_chief_exp')->nullable();
            $table->text('staff_shariah_name')->nullable();
            $table->text('staff_shariah_religion')->nullable();
            $table->text('staff_shariah_qualifications')->nullable();
            $table->text('staff_shariah_relevant')->nullable();
            $table->text('staff_shariah_exp')->nullable();
            $table->text('staff_quality_name')->nullable();
            $table->text('staff_quality_religion')->nullable();
            $table->text('staff_quality_qualifications')->nullable();
            $table->text('staff_quality_relevant')->nullable();
            $table->text('staff_quality_exp')->nullable();
            $table->text('staff_manage_name')->nullable();
            $table->text('staff_manage_religion')->nullable();
            $table->text('staff_manage_qualifications')->nullable();
            $table->text('staff_manage_relevant')->nullable();
            $table->text('staff_manage_exp')->nullable();
            $table->text('staff_audit_name')->nullable();
            $table->text('staff_audit_religion')->nullable();
            $table->text('staff_audit_qualifications')->nullable();
            $table->text('staff_audit_field')->nullable();
            $table->text('staff_audit_exp')->nullable();
            $table->text('staff_list_name')->nullable();
            $table->text('staff_list_religion')->nullable();
            $table->text('staff_list_qualifications')->nullable();
            $table->text('staff_list_field')->nullable();
            $table->text('staff_list_exp')->nullable();
            $table->text('scop_cat_code')->nullable();
            $table->text('scop_category')->nullable();
            $table->text('scop_cat_exap')->nullable();
            $table->text('org_quality')->nullable();
            $table->text('org_quality_comment')->nullable();
            $table->text('org_policy')->nullable();
            $table->text('org_policy_comment')->nullable();
            $table->text('org_procedures')->nullable();
            $table->text('org_procedures_comment')->nullable();
            $table->text('org_manual')->nullable();
            $table->text('org_manual_comment')->nullable();
            $table->text('org_shariah')->nullable();
            $table->text('org_shariah_comment')->nullable();
            $table->text('org_qmr')->nullable();
            $table->text('org_qmr_comment')->nullable();
            $table->text('org_hcb')->nullable();
            $table->text('org_hcb_comment')->nullable();
            $table->text('org_referred')->nullable();
            $table->text('org_referred_comment')->nullable();
            $table->text('quality_doc')->nullable();
            $table->text('quality_doc_comment')->nullable();
            $table->text('quality_frequently')->nullable();
            $table->text('quality_frequently_comment')->nullable();
            $table->text('quality_records')->nullable();
            $table->text('quality_records_comment')->nullable();
            $table->text('quality_hcb')->nullable();
            $table->text('quality_hcb_comment')->nullable();
            $table->text('quality_review')->nullable();
            $table->text('quality_review_comment')->nullable();
            $table->text('halal_quality')->nullable();
            $table->text('halal_quality_comment')->nullable();
            $table->text('halal_appropriate')->nullable();
            $table->text('halal_appropriate_comment')->nullable();
            $table->text('halal_doc')->nullable();
            $table->text('halal_doc_comment')->nullable();
            $table->text('proced_doc')->nullable();
            $table->text('proced_doc_comment')->nullable();
            $table->text('proced_referred')->nullable();
            $table->text('proced_referred_comment')->nullable();
            $table->text('record_prescribed')->nullable();
            $table->text('record_prescribed_comment')->nullable();
            $table->text('record_arrang')->nullable();
            $table->text('record_arrang_comment')->nullable();
            $table->text('record_hcb')->nullable();
            $table->text('record_hcb_comment')->nullable();
            $table->text('complaint_hcb')->nullable();
            $table->text('complaint_hcb_comment')->nullable();
            $table->text('complaint_record')->nullable();
            $table->text('complaint_record_comment')->nullable();
            $table->text('subcontract_hcb')->nullable();
            $table->text('subcontract_hcb_comment')->nullable();
            $table->text('subcontract_cb')->nullable();
            $table->text('subcontract_cb_comment')->nullable();
            $table->text('subcontract_register')->nullable();
            $table->text('subcontract_register_comment')->nullable();
            $table->text('outside_doc')->nullable();
            $table->text('outside_doc_comment')->nullable();
            $table->text('outside_hcb')->nullable();
            $table->text('outside_hcb_comment')->nullable();
            $table->text('compliance_check')->nullable();
            $table->text('compliance_check_area')->nullable();
            $table->text('rectified_date')->nullable();
            $table->text('approvals_name')->nullable();
            $table->text('approvals_scope')->nullable();
            $table->text('approvals_start_date')->nullable();
            $table->text('approvals_end_date')->nullable();
            $table->text('declaration_halal')->nullable();
            $table->text('declaration_extension')->nullable();
            $table->text('declaration_signed')->nullable();
            $table->text('declaration_date')->nullable();

            $table->text('category')->nullable();

            $table->unsignedBigInteger('user_id')->nullable();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('halal_certification_bodies');
    }
};
