<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('certification_bodies', function (Blueprint $table) {
            $table->id();
            $table->string('certification_body')->nullable();
            $table->string('general_address')->nullable();
            $table->string('postcode')->nullable();
            $table->string('tel')->nullable();
            $table->string('fax')->nullable();
            $table->string('contact_name')->nullable();
            $table->string('designation')->nullable();
            $table->string('person_address')->nullable();
            $table->string('person_postcode')->nullable();
            $table->string('person_tel')->nullable();
            $table->string('person_fax')->nullable();
            $table->string('person_email')->nullable();
            $table->string('sub_offices')->nullable();
            $table->string('offices_cities')->nullable();
            $table->string('new_accreditation')->nullable();
            $table->string('qms')->nullable();
            $table->string('EMS')->nullable();
            $table->string('FSMS')->nullable();
            $table->string('ISO_45001')->nullable();
            $table->string('ISO_13485')->nullable();
            $table->string('other_management')->nullable();
            $table->string('extension_scope')->nullable();
            $table->string('chack_quality_manual')->nullable();
            $table->string('chack_procedures')->nullable();
            $table->string('chack_list_staff')->nullable();
            $table->string('chack_list_certified')->nullable();
            $table->string('chack_applicant')->nullable();
            $table->string('chack_proof')->nullable();
            $table->string('chack_filled_form')->nullable();
            $table->text('selves_title')->nullable();
            $table->text('selves_name')->nullable();
            $table->text('selves_position')->nullable();
            $table->text('selves_parent_organization')->nullable();
            $table->text('selves_parent_relationship')->nullable();
            $table->text('selves_parent_address')->nullable();
            $table->text('selves_parent_postcode')->nullable();
            $table->text('selves_parent_tel')->nullable();
            $table->text('selves_parent_fax')->nullable();
            $table->text('selves_invoicing_organization')->nullable();
            $table->text('selves_invoicing_address')->nullable();
            $table->text('selves_invoicing_postcode')->nullable();
            $table->text('selves_invoicing_tel')->nullable();
            $table->text('selves_invoicing_fax')->nullable();
            $table->text('selves_individual')->nullable();
            $table->text('selves_public')->nullable();
            $table->text('selves_private')->nullable();
            $table->text('selves_tech')->nullable();
            $table->text('selves_nationalised')->nullable();
            $table->text('selves_academic')->nullable();
            $table->text('selves_other_describe')->nullable();
            $table->text('selves_activities')->nullable();
            $table->text('selves_main_activities')->nullable();
            $table->text('selves_consultant_name')->nullable();
            $table->text('selves_consultant_Org')->nullable();
            $table->text('selves_consultant_address')->nullable();
            $table->text('selves_consultant_postcode')->nullable();
            $table->text('selves_consultant_tel')->nullable();
            $table->text('selves_consultant_fax')->nullable();
            $table->text('selves_consultant_email')->nullable();
            $table->text('staff_chief_name')->nullable();
            $table->text('staff_chief_qualifications')->nullable();
            $table->text('staff_chief_relevant')->nullable();
            $table->text('staff_chief_exp')->nullable();
            $table->text('staff_quality_name')->nullable();
            $table->text('staff_quality_qualifications')->nullable();
            $table->text('staff_quality_relevant')->nullable();
            $table->text('staff_quality_exp')->nullable();
            $table->text('staff_manag_name')->nullable();
            $table->text('staff_manag_qualifications')->nullable();
            $table->text('staff_manag_relevant')->nullable();
            $table->text('staff_manag_exp')->nullable();
            $table->text('staff_assessor_name')->nullable();
            $table->text('staff_assessor_qualifications')->nullable();
            $table->text('staff_assessor_auditing')->nullable();
            $table->text('staff_assessor_exp')->nullable();
            $table->text('staff_sub_name')->nullable();
            $table->text('staff_sub_qualifications')->nullable();
            $table->text('staff_sub_auditing')->nullable();
            $table->text('staff_sub_exp')->nullable();
            $table->text('scop_technical_a')->nullable();
            $table->text('scop_iaf_a')->nullable();
            $table->text('scop_economic_a')->nullable();
            $table->text('scop_technical_b')->nullable();
            $table->text('scop_iaf_b')->nullable();
            $table->text('scop_economic_b')->nullable();
            $table->text('scop_technical_c')->nullable();
            $table->text('scop_iaf_c')->nullable();
            $table->text('scop_economic_c')->nullable();
            $table->text('scop_cluster')->nullable();
            $table->text('scop_category')->nullable();
            $table->text('scop_subcategory')->nullable();
            $table->text('scop_activity')->nullable();
            $table->text('scop_main_tech')->nullable();
            $table->text('scop_areas')->nullable();
            $table->text('scop_product')->nullable();
            $table->text('scop_uncertainty')->nullable();
            $table->text('scop_standard')->nullable();
            $table->text('scop_quality')->nullable();
            $table->text('scop_major_name')->nullable();
            $table->text('scop_major_model')->nullable();
            $table->text('scop_major_working')->nullable();
            $table->text('scop_major_minimum')->nullable();
            $table->text('scop_major_lastdate')->nullable();
            $table->text('scop_major_duedate')->nullable();
            $table->text('scop_major_test')->nullable();
            $table->text('scop_reference_name')->nullable();
            $table->text('scop_reference_source')->nullable();
            $table->text('scop_reference_date_ex')->nullable();
            $table->text('scop_reference_traceability')->nullable();
            $table->text('scop_reference_purpose')->nullable();
            $table->text('scop_proficiency_product')->nullable();
            $table->text('scop_proficiency_details')->nullable();
            $table->text('scop_proficiency_date')->nullable();
            $table->text('scop_proficiency_organizing')->nullable();
            $table->text('scop_proficiency_performance')->nullable();
            $table->text('scop_proficiency_corrective')->nullable();
            $table->text('quality_consider')->nullable();
            $table->text('quality_noncompliance')->nullable();
            $table->string('quality_rect_date')->nullable();
            $table->text('quality_name')->nullable();
            $table->text('quality_accreditation')->nullable();
            $table->date('quality_start_date')->nullable();
            $table->date('quality_expiry_date')->nullable();
            $table->text('signed')->nullable();
            $table->date('date')->nullable();

            $table->text('category')->nullable();

            $table->unsignedBigInteger('user_id')->nullable();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('certification_bodies');
    }
};
