<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class InspectionBody extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'inspection_body',
        'general_address',
        'postcode',
        'tel',
        'fax',
        'contact_name',
        'designation',
        'person_address',
        'person_postcode',
        'person_tel',
        'person_fax',
        'person_email',
        'sub_offices',
        'offices_cities',
        'new_accreditation',
        'extension_scope',
        'chack_quality_manual',
        'chack_applicant',
        'chack_Completely',
        'chack_calibration',
        'chack_copies',
        'chack_internal',
        'chack_vitae',
        'chack_performed',
        'chack_filled_form',
        'organized_title',
        'organized_name',
        'organized_position',
        'organized_parent_organization',
        'organized_parent_relationship',
        'organized_parent_address',
        'organized_parent_postcode',
        'organized_parent_tel',
        'organized_parent_fax',
        'organized_invoicing_organization',
        'organized_invoicing_address',
        'organized_invoicing_postcode',
        'organized_invoicing_tel',
        'organized_invoicing_fax',
        'organized_legal_status',
        'organized_inspection',
        'organized_specify',
        'organized_activity',
        'organized_describe',
        'organized_body_type',
        'organized_other_name',
        'organized_other_scope',
        'organized_other_period',
        'organized_consult_name',
        'organized_consult_Org',
        'organized_consult_address',
        'organized_consult_postcode',
        'organized_consult_tel',
        'organized_consult_fax',
        'organized_consult_email',
        'staff_chief_name',
        'staff_chief_qualifications',
        'staff_chief_relevant',
        'staff_chief_exp',
        'staff_quality_name',
        'staff_quality_qualifications',
        'staff_quality_relevant',
        'staff_quality_exp',
        'staff_manag_name',
        'staff_manag_qualifications',
        'staff_manag_relevant',
        'staff_manag_exp',
        'staff_inspect_name',
        'staff_inspect_qualifications',
        'staff_inspect_auditing',
        'staff_inspect_exp',
        'staff_sub_name',
        'staff_sub_qualifications',
        'staff_sub_auditing',
        'staff_sub_exp',
        'scop_inspect_des',
        'scop_range',
        'scop_method',
        'scop_equipment',
        'scop_calibration',
        'scop_economic_b',
        'scop_last_calib',
        'declaration_type_a',
        'declaration_type_b',
        'declaration_type_c',
        'declaration_signed',
        'declaration_date',
        'category',
    ];
}
