<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProficiencyTesting extends Model
{
    use HasFactory;
    protected $fillable = [
        'user_id',
        'organisation',
        'address',
        'postcode',
        'tel',
        'fax',
        'contact_name',
        'designation',
        'person_address',
        'person_postcode',
        'person_tel',
        'person_fax',
        'person_email',
        'chack_accreditation',
        'chack_extension',
        'chack_chemical',
        'chack_textile',
        'chack_environment',
        'chack_biological',
        'chack_clinical',
        'chack_dimensional',
        'chack_mechanical',
        'chack_materials',
        'chack_metallurgical',
        'chack_others',
        'chack_manual',
        'chack_procedures',
        'chack_technical',
        'chack_testing',
        'chack_complete',
        'chack_staff',
        'chack_relevant',
        'chack_suppliers',
        'chack_calibration',
        'chack_report',
        'selves_title',
        'selves_name',
        'selves_position',
        'selves_parent_organization',
        'selves_address',
        'selves_postcode',
        'selves_tel',
        'selves_fax',
        'selves_invoicing_organization',
        'selves_invoicing_address',
        'selves_invoicing_postcode',
        'selves_invoicing_tel',
        'selves_invoicing_fax',
        'selves_individual',
        'selves_public',
        'selves_private',
        'selves_learned',
        'selves_industry',
        'selves_academic',
        'selves_other_describe',
        'selves_activity',
        'selves_cab_activity',
        'selves_own_org',
        'selves_other_org',
        'staff_name',
        'staff_qualifications',
        'staff_relevant',
        'staff_exp',
        'staff_quality_name',
        'staff_quality_qualifications',
        'staff_quality_relevant',
        'staff_quality_exp',
        'staff_coordinator_name',
        'staff_coordinator_qualifications',
        'staff_coordinator_relevant',
        'staff_coordinator_exp',
        'staff_statistian_name',
        'staff_statistian_qualifications',
        'staff_statistian_relevant',
        'staff_statistian_exp',
        'scop_parameter',
        'scop_testing',
        'scop_round',
        'scop_equipment',
        'scop_last_date',
        'scop_next_date',
        'scop_calibration',
        'scop_details',
        'scop_comments',
        'approvals_name',
        'approvals_scope',
        'approvals_start_date',
        'approvals_end_date',
        'declaration_applicant',
        'declaration_extension',
        'declaration_signed',
        'declaration_date',
        'category',
    ];

}
